<?php

/**
 * @file
 * Hooks.
 */

use Drupal\media\MediaInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function damo_assets_thumbnails_media_presave(MediaInterface $media) {
  // @todo: Remove custom-thumbnail, expose thumbnail on forms, etc?
  if (
    $media->bundle() === 'video_file'
    && $media->get('field_custom_thumbnail')->isEmpty()
  ) {
    /** @var \Drupal\damo_assets_thumbnails\Service\VideoThumbnail $service */
    $service = Drupal::service('damo_assets_thumbnails.video_thumbnail');
    $thumbnail = $service->generateAssetThumbnail($media);
    $media->set('thumbnail', $thumbnail);
  }
}
